services:
  postgres:
    image: postgres:15-alpine
    container_name: gymDb
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: senhasegura
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-vol:/var/lib/postgresql/volumeData
    networks:
      - gym-network

volumes:
  postgres-vol:

networks:
  gym-network:
    driver: bridge